### ISSUE TITLE
`validate_addr` should call `validate_2822_addr `, not `validate_2822`

### ISSUE THREAD

**Issue by blowmage** [larb/email_address_validator#2]
The documentation and implementation are at odds. It looks like line 55 should be calling `validate_2822_addr ` though.

https://github.com/larb/email_address_validator/blob/master/lib/email_address_validator.rb#L54-L55

**Comment by veganstraightedge** [comment]
@blowmage Wanna submit a pull request?

**Comment by blowmage** [comment]
I forked to create the pr, but am having a hard time getting the tests to pass. Are they in a known good state?

**Comment by veganstraightedge** [comment]
@evanphx @ajsharp 👆
