### ISSUE TITLE
merge @bookis' fixes

### ISSUE THREAD

**Issue by veganstraightedge** [larb/email_address_validator#3]
https://github.com/bookis/email_address_validator/commits/master

@bookis fixed some things to get email_address_validator working on dateedge/website. It works for us and our needs.

Currently, we're running on Heroku + Rubinius 2.0.0.m8. 

But it needs to be updated for MRI 2.0+.

```
/lib/email_address_validator/rfc822-parser.rb:486: invalid multibyte escape: /\A(?-mix:[^\]\x00-\x20 \x7F\x80-\xFF()<>@,;:\\".\[]+)/ (SyntaxError)
invalid multibyte escape: /\A(?-mix:[^)\\\x0D\x80-\xFF(]+)/
invalid multibyte escape: /\A(?-mix:[^\]\\\x0D\x80-\xFF\[]+)/
invalid multibyte escape: /\A(?-mix:[^"\\\x0D\x80-\xFF]+)/
```

**Comment by evanphx** [comment]
I bumped the version to 1.0.0 (since this is obviously stable based on the number of commits) and pushed it.

**Comment by veganstraightedge** [comment]
Woohoo! Thanks @evanphx.
